name: Test

on:
  push:
    branches: [master,dev]
  pull_request:
    branches: [master,dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn

      - name: Run tests:cov
        run: yarn test:cov

      - name: Run test:ci
        run: yarn test:ci
      
      - uses: devmasx/coverage-check-action@v1.1.0
        with:
          type: simplecov
          result_path: coverage/coverage-final.json
          min_coverage: 90
          token: ${{secrets.GITHUB_TOKEN}}