name: Test

on:
  push:
    branches: [master,dev]
  pull_request:
    branches: [master,dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install dependencies
        run: yarn

      - name: Run tests:cov
        run: yarn test:cov

      - name: Run test:ci
        run: yarn test:ci
      
      - name: Monitor coverage
        uses: slavcodev/coverage-monitor-action@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          clover_file: "coverage/clover.xml"
          threshold_alert: 10
          threshold_warning: 50